// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-yBU31iRJiJi8kvXNlT3iPexZWwBsVjw',
    appId: '1:809175849633:web:a889af9540529f411faee0',
    messagingSenderId: '809175849633',
    projectId: 'bpi-examen',
    authDomain: 'bpi-examen.firebaseapp.com',
    storageBucket: 'bpi-examen.appspot.com',
    measurementId: 'G-YEJQHDRDQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6thyCAfsoOZpd8fZU5fPtLIkMTNR5iH4',
    appId: '1:809175849633:android:a794282a9f1b6f331faee0',
    messagingSenderId: '809175849633',
    projectId: 'bpi-examen',
    storageBucket: 'bpi-examen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC88cn5Zx2BlWcwxf4SrvBPaz4hsZ6Yhbw',
    appId: '1:809175849633:ios:afce5444f66a96091faee0',
    messagingSenderId: '809175849633',
    projectId: 'bpi-examen',
    storageBucket: 'bpi-examen.appspot.com',
    iosClientId: '809175849633-cmbj5bs2thstag2bk7jie6q98tk1dl35.apps.googleusercontent.com',
    iosBundleId: 'com.example.bpiExamen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC88cn5Zx2BlWcwxf4SrvBPaz4hsZ6Yhbw',
    appId: '1:809175849633:ios:afce5444f66a96091faee0',
    messagingSenderId: '809175849633',
    projectId: 'bpi-examen',
    storageBucket: 'bpi-examen.appspot.com',
    iosClientId: '809175849633-cmbj5bs2thstag2bk7jie6q98tk1dl35.apps.googleusercontent.com',
    iosBundleId: 'com.example.bpiExamen',
  );
}
